name: test

on: [push]

jobs:
  web_test:
    #run location
    runs-on: ubuntu-latest
    #what does
    steps:
      #get repository
      - uses: actions/checkout@v3
        #configuring java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: Xotabu4/selenoid-github-action@v2
        #run tests
      - run: ./gradlew clean web_test -Dselenide.remote=http://localhost:4444/wd/hub
